stages:
  - build
  - test
  - release
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  SAST_EXCLUDED_ANALYZERS: "gosec-sast"

build-code-job:
  stage: build
  cache:
    - key: npm
      paths:
        - frontend/.npm/
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - cd ..
    - mkdir -p $CI_PROJECT_DIR/momo-store-${VERSION}/public_html
    - mv frontend/dist/ $CI_PROJECT_DIR/momo-store-${VERSION}/public_html
  artifacts:
    paths:
      - $CI_PROJECT_DIR/momo-store-${VERSION}/public_html

sonarqube-frontend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner \
        -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONT} \
        -Dsonar.sources=. \
        -Dsonar.host.url=${SONARQUBE_URL} \
        -Dsonar.login=${SONAR_LOGIN} \
        -Dsonar.projectName=${SONAR_PROJECT_NAME_FRONT}

upload-release:
  stage: release
  dependencies:
    - build-code-job
  script:
    - tar czvf momo-store-${VERSION}.tar.gz momo-store-${VERSION}/go-build
    - >
      curl -v -u "${NEXUS_REPO_USER}:$(echo $NEXUS_REPO_PASS | base64 -d)" --upload-file sausage-store-${VERSION}.tar.gz ${NEXUS_REPO_FRONTEND_URL}/momo-store-frontend/momo-store/$VERSION/momo-store-front-$VERSION.tar.gz