stages:
  - test
  - build
  - release
  - deploy-staging
  - deploy-production

include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
  - project: 'anton-alekseyev/sausage-store'
    file: 'template.gitlab-ci.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  SAST_EXCLUDED_ANALYZERS: "eslint,nodejs-scan-sast"

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/backend/.go
  before_script:
    - mkdir -p backend/.go
  cache:
    paths:
      - .go/pkg/mod/

format:
  stage: test
  image: golang:1.17
  extends: .go-cache
  script:
    - cd backend
    - go vet ./...
    - go test -v ./...

compile:
  stage: build
  image: golang:1.17
  extends: .go-cache
  script:
    - cd backend
    - mkdir -p $CI_PROJECT_DIR/momo-store-${VERSION}/go-build
    - go build -o $CI_PROJECT_DIR/momo-store-${VERSION}/go-build ./...
  artifacts:
    paths:
      - $CI_PROJECT_DIR/momo-store-${VERSION}/go-build

build-docker-kaniko:
  stage: build
  cache: [ ]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  extends: .docker-registry-auth
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --cache-copy-layers
      --destination "${CI_REGISTRY_IMAGE}/$DOCKER_BACKEND_NAME:${VERSION}"
      --cache=true

gosec-sast:
  extends: .go-cache
  stage: test
  script:
    - cd backend
    - /analyzer run  --target-dir ${CI_PROJECT_DIR}/backend/ --artifact-dir ${CI_PROJECT_DIR}/backend/
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/backend/gl-sast-report.json
    reports:
      sast: gl-sast-report.json

sonarqube-backend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd backend
    - >
      sonar-scanner \
        -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK} \
        -Dsonar.sources=. \
        -Dsonar.host.url=${SONARQUBE_URL} \
        -Dsonar.login=${SONAR_LOGIN} \
        -Dsonar.projectName=${SONAR_PROJECT_NAME_BACK}

upload-release:
  stage: release
  dependencies:
    - compile
  script:
    - tar czvf momo-store-${VERSION}.tar.gz momo-store-${VERSION}/go-build
    - >
      curl -v -u "${NEXUS_REPO_USER}:$(echo $NEXUS_REPO_PASS | base64 -d)" --upload-file momo-store-${VERSION}.tar.gz ${NEXUS_REPO_BACKEND_URL}/momo-store-backend/momo-store/$VERSION/momo-store-back-$VERSION.tar.gz

upload-docker-latest:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/$DOCKER_BACKEND_NAME:$VERSION latest

deploy-helm-staging:
  stage: deploy-staging
  extends: .deploy-helm
  variables:
    MOMO_STORE_URL: $MOMO_STORE_URL_STAGING
    ENVIRONMENT_TYPE: staging
  environment:
    name: momo-staging
    url: https://$MOMO_STORE_URL_STAGING

deploy-helm-production:
  stage: deploy-production
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
      when: manual
    - when: never
  extends: .deploy-helm
  variables:
    MOMO_STORE_URL: $MOMO_STORE_URL_PRODUCTION
    ENVIRONMENT_TYPE: production
  environment:
    name: momo-production
    url: https://$MOMO_STORE_URL_PRODUCTION

.deploy-helm:
  image: lwolf/helm-kubectl-docker:v1.21.1-v3.6.0
  before_script:
    - mkdir -p $HOME/.kube
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - echo -n $KUBE_CA | base64 -d > $HOME/.kube/ca.pem
  script:
    - helm repo add nexus $NEXUS_REPO_HELM_URL --username ${NEXUS_REPO_USER} --password $(echo $NEXUS_REPO_PASS | base64 -d)
    - helm repo update
    - >
      helm upgrade --install momo-store-$ENVIRONMENT_TYPE \
        --set global.environment=$ENVIRONMENT_TYPE \
        --set global.backendPort=$BACKEND_PORT \
        --set secrets.dockerConfigJson=${DOCKER_CONFIG_JSON} \
        --set backend.image.tag=$VERSION \
        --atomic --timeout 15m \
        --namespace momo-store-$ENVIRONMENT_TYPE \
        --reuse-values \
          nexus/momo-store
  after_script:
    - rm $HOME/.kube/config